version: '3.8'

services:
  # Define our cow-coffee-cafe application service
  cow-coffee-cafe:
    # Build the Docker image from the current directory
    build:
      context: .
      dockerfile: Dockerfile

    # Name the container for easy identification
    container_name: cow-coffee-cafe-app

    # Map port 4173 inside the container to port 4501 on our host machine
    # This means you can access the app at http://localhost:4501
    ports:
      - "4501:4173"

    # Restart policy - restart the container if it crashes
    restart: unless-stopped

    # Environment variables (we can add more later if needed)
    environment:
      - NODE_ENV=production

    # For development, we can override the command to run in dev mode
    # This is commented out for now, but useful for development
    # command: npm run dev -- --host 0.0.0.0

    # If we want to mount our source code for development (hot reloading)
    # This is commented out for production build, but useful for development
    # volumes:
    #   - .:/app
    #   - /app/node_modules